### ISSUE TITLE
Use dynamicly drawn circle arcs so this component doesn't have to override ImageView

### ISSUE THREAD

**Issue by carignanboy1** [anupcowkur/Android-Wheel-Menu#2]
This way various labels could be used on each division of the Wheel-Menu. Also, if the class can generate its own drawable, it could render in Eclipse's Graphical Layout view for layouts.

**Comment by carignanboy1** [comment]
hey @anupcowkur, check out the app I was making: https://play.google.com/store/apps/details?id=com.alexismorin.typewheel

I've completely rewritten the wheel so that it supports dynamically drawn segments, background colours and labels. I'll be putting the project up on GitHub soon enough for everyone to use.

**Comment by anupcowkur** [comment]
Great. Leave a link here when you do.
